In [2]:
import pandas as pd

In [17]:
## Azure
vm_table_data_link = "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vmtable/vmtable.csv.gz"
vm_table_data = pd.read_csv(vm_table_data_link, compression = "gzip")
vm_table_data.head()

,71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB,GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR,2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==,558300,1673700,91.776885421193157,0.72887880462586729,20.759629514971522,Delay-insensitive,8,32
0,rKggHO/04j31UFy65mDTwtjdMQL/G03xWfl3xGeiilB4/W...,ub4ty8ygwOECrIz7eaZ/9hDwnCsERvZ3nJJ03sDSpD85et...,+ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHFmyJ...,424500,425400,37.879261,3.325358,37.879261,Unknown,4,32
1,YrR8gPtBmfNaOdnNEW5If1SdTqQgGQHEnLHGPjySt53bKW...,9LrdYRcUfGbmL2fFfLR/JUg2OTkjGRe3iluwIhDRPnPDPa...,GEyIElfPSFupze8T+T1niQMepeqG88VpLNuxUMyIDbz8VF...,1133100,1133700,0.304368,0.220553,0.304368,Unknown,4,32
2,xzQ++JF1UAkh70CDhmzkiOo+DQn+E2TLErCFKEmSswv1pl...,0XnZZ8sMN5HY+Yg+0dykYB5oenlgsrCpzpgFSvn/MX42Ze...,7aCQS6fPUw9rwCPiqvghk/WCEbMV3KgNJjA+sssdfY5Ybl...,0,2591400,98.573424,30.340054,98.212503,Interactive,2,4
3,vZEivnhabRmImDr+JqKqZnpIM3WxtypwoxjfjnklR/idyR...,HUGaZ+piPP4eHjycCBki2yq0raJywdzrVuriR6nQceH3hA...,/s/D5VtTQDxyS6wq7N/VQAMczx61Ny1Ut3a3iFmDSOCXxp...,228300,229800,82.581449,13.876299,82.581449,Unknown,2,4
4,MqvcZ6Au5ouI6if56MJHmoSqHtX8oRv0dPkaxCId3aUcr1...,p14cXGYqCKCcF7b7OdV6bdr/0gCim+u1LeqKoyEkyNNMWf...,ZFCk80sIQzr43FUSqy2DOrcvBhuQkyfVz7gus8SORhyBxC...,1395600,1397700,0.097875,0.035215,0.097875,Unknown,4,32

In [ ]:
vm_table_column_names_schema = ["vm_id", "subscription_id", "deployment_id", "vm_creation_timestamp", "vm_deletion_timestamp", "max_cpu", "avg_cpu", "p95_max_cpu", "vm_category", "vm_core_count", "vm_memory"]
vm_table_data.columns = vm_table_column_names_schema
vm_table_data.head()

,vm_id,subscription_id,deployment_id,vm_creation_timestamp,vm_deletion_timestamp,max_cpu,avg_cpu,p95_max_cpu,vm_category,vm_core_count,vm_memory
0,rKggHO/04j31UFy65mDTwtjdMQL/G03xWfl3xGeiilB4/W...,ub4ty8ygwOECrIz7eaZ/9hDwnCsERvZ3nJJ03sDSpD85et...,+ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHFmyJ...,424500,425400,37.879261,3.325358,37.879261,Unknown,4,32
1,YrR8gPtBmfNaOdnNEW5If1SdTqQgGQHEnLHGPjySt53bKW...,9LrdYRcUfGbmL2fFfLR/JUg2OTkjGRe3iluwIhDRPnPDPa...,GEyIElfPSFupze8T+T1niQMepeqG88VpLNuxUMyIDbz8VF...,1133100,1133700,0.304368,0.220553,0.304368,Unknown,4,32
2,xzQ++JF1UAkh70CDhmzkiOo+DQn+E2TLErCFKEmSswv1pl...,0XnZZ8sMN5HY+Yg+0dykYB5oenlgsrCpzpgFSvn/MX42Ze...,7aCQS6fPUw9rwCPiqvghk/WCEbMV3KgNJjA+sssdfY5Ybl...,0,2591400,98.573424,30.340054,98.212503,Interactive,2,4
3,vZEivnhabRmImDr+JqKqZnpIM3WxtypwoxjfjnklR/idyR...,HUGaZ+piPP4eHjycCBki2yq0raJywdzrVuriR6nQceH3hA...,/s/D5VtTQDxyS6wq7N/VQAMczx61Ny1Ut3a3iFmDSOCXxp...,228300,229800,82.581449,13.876299,82.581449,Unknown,2,4
4,MqvcZ6Au5ouI6if56MJHmoSqHtX8oRv0dPkaxCId3aUcr1...,p14cXGYqCKCcF7b7OdV6bdr/0gCim+u1LeqKoyEkyNNMWf...,ZFCk80sIQzr43FUSqy2DOrcvBhuQkyfVz7gus8SORhyBxC...,1395600,1397700,0.097875,0.035215,0.097875,Unknown,4,32

In [ ]:
def get_vm_cpu_readings(index):
    vm_cpu_reading_link = "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vm_cpu_readings/vm_cpu_readings-file-" + str(index) + "-of-195.csv.gz"
    curr_vm_cpu_reading_data = pd.read_csv(vm_cpu_reading_link, compression = "gzip")
    return curr_vm_cpu_reading_data

In [ ]:
cpu_vm_reading_data_1 = get_vm_cpu_readings(1)
cpu_vm_reading_data_1.head()

,0,yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X,19.898441030801841,24.996361191759995,22.630672687116984
0,0,gVb4X4iS13nJrM0KZsy7SrHzWAHix0CEPlK7/deV5vkwjt...,14.281488,20.028324,17.250655
1,0,f8BtQHczrXFjnVxWl8Hqm1kH9UD/8nCvtXCLiFvVRvamqa...,1.655368,23.138685,8.533818
2,0,8xjtVrJRJAyArNlbRgCftoNQOZiWl2eRP6uQavL9+6IULT...,47.501061,52.940579,50.045584
3,0,zTE3f0H2n43tW+PA3OdonjUTWWxeyzF7xJk9QH9s/487J/...,1.724155,12.889580,4.833578
4,0,oJXXVhFJaulRsMKo8iZ7PWewFKPbuwQtyXbR0IjQOWli8G...,11.927168,20.426842,16.279067

In [ ]:
cpu_vm_column_names = ["timestamp", "vm_id", "min_cpu", "max_cpu", "avg_cpu"]
cpu_vm_reading_data_1.columns = cpu_vm_column_names
cpu_vm_reading_data_1.head()

,timestamp,vm_id,min_cpu,max_cpu,avg_cpu
0,0,gVb4X4iS13nJrM0KZsy7SrHzWAHix0CEPlK7/deV5vkwjt...,14.281488,20.028324,17.250655
1,0,f8BtQHczrXFjnVxWl8Hqm1kH9UD/8nCvtXCLiFvVRvamqa...,1.655368,23.138685,8.533818
2,0,8xjtVrJRJAyArNlbRgCftoNQOZiWl2eRP6uQavL9+6IULT...,47.501061,52.940579,50.045584
3,0,zTE3f0H2n43tW+PA3OdonjUTWWxeyzF7xJk9QH9s/487J/...,1.724155,12.889580,4.833578
4,0,oJXXVhFJaulRsMKo8iZ7PWewFKPbuwQtyXbR0IjQOWli8G...,11.927168,20.426842,16.279067

In [ ]:
deployment_table_link = "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/deployments/deployments.csv.gz"
deployment_table_data = pd.read_csv(deployment_table_link, compression = "gzip")
deployment_table_data.head()

,+EZ/AWPlMyGxKY9bSsXYV+nf3hgJLlR7kNJPNNJDerKjM3P3NIjsmoIBcySwoQwPj8fnC+cxTPRCj5oX6YlU0g==,11
0,+ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHF+kd...,9
1,/+3IQ9csEUWlX/OR5lHSiUh+EH54WfI9nfpjniqCk/cQig...,2
2,/5mEvsIGOul7DM6xGef5rE1u0TZg4N7dkSmotRO1D87M8i...,23
3,/DrUXkHMnF+IdCiFWiT06P/2CZBiZ7Y1WLfTZGV7hU868C...,11
4,/FKHfSYGMMMKmXeI5gtrYcQUyd1TkudSsBa6poHIRO3gwm...,1

In [4]:
deployment_table_cols = ["deployment_id", "deployment_size"]
deployment_table_data.columns = deployment_table_cols
deployment_table_data.head()

                                       deployment_id  deployment_size
0  +ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHF+kd...                9
1  /+3IQ9csEUWlX/OR5lHSiUh+EH54WfI9nfpjniqCk/cQig...                2
2  /5mEvsIGOul7DM6xGef5rE1u0TZg4N7dkSmotRO1D87M8i...               23
3  /DrUXkHMnF+IdCiFWiT06P/2CZBiZ7Y1WLfTZGV7hU868C...               11
4  /FKHfSYGMMMKmXeI5gtrYcQUyd1TkudSsBa6poHIRO3gwm...                1

In [5]:
subscriptions_table_link = "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/subscriptions/subscriptions.csv.gz"
subscriptions_table_data = pd.read_csv(subscriptions_table_link, compression = "gzip")
subscriptions_table_data.head()

,/YdjZT4MloSQErgc+pr6xPdxhPDK2DdCHz3v1uYvb+RQPbwdjOnjqeC5cgPPyFT2,418200,2
0,1owRC8fAiTkftDDmemUYdXtzzmnuOoKN1keoqCE0SkllaU...,0,8947
1,1wYls1fw1ahqoRuYgqTwW1CWwFCA+GhM8bUdE2ZnE3QEUi...,0,6057
2,37GxzuLNVu9neuiSXk/RMGqW2vCOIkF0aSGdIdR5QaMqSj...,0,31
3,4JEvQIV0SLuz6P+rPxPQCIZTOsDW2Y9wUPPMwQxL4sJ0ob...,0,1
4,4YfyCAdDFb2lh/CDVojPdIR+5v2HeMvEUrv0DMMgc9FfAW...,0,1

In [10]:
subscriptions_table_cols = ["subscription_id", "timestamp_first_vm_created", "number_vms_created"]
subscriptions_table_data.columns = subscriptions_table_cols
subscriptions_table_data.head()

,subscription_id,timestamp_first_vm_created,number_vms_created
0,1owRC8fAiTkftDDmemUYdXtzzmnuOoKN1keoqCE0SkllaU...,0,8947
1,1wYls1fw1ahqoRuYgqTwW1CWwFCA+GhM8bUdE2ZnE3QEUi...,0,6057
2,37GxzuLNVu9neuiSXk/RMGqW2vCOIkF0aSGdIdR5QaMqSj...,0,31
3,4JEvQIV0SLuz6P+rPxPQCIZTOsDW2Y9wUPPMwQxL4sJ0ob...,0,1
4,4YfyCAdDFb2lh/CDVojPdIR+5v2HeMvEUrv0DMMgc9FfAW...,0,1